log4j.rootLogger = INFO, FA

log4j.appender.FA = org.apache.log4j.FileAppender
log4j.appender.FA.File = d:/log4jfile.html
log4j.appender.FA.layout = org.apache.log4j.HTMLLayout
log4j.appender.FA.layout.Title = My Log Messages